x-uffizzi:
  ingress:
    service: app
    port: 80
services:
    argo-x:
        container_name: app
        ports:
            - '80:3000'
        restart: always
        logging:
            options:
                max-size: 1m
        image: 'fscarmen/argo-x:latest'
